#ifndef BTN_EVENT_HANDLING_SETTINGS_H
#define BTN_EVENT_HANDLING_SETTINGS_H

#define NUM_TO_KB(x) x * 1024
#define DS4_BTN_EVENT_TASK_SIZE 3 // In kB
#define DS4_BTN_EVENT_TASK_NAME "DS4 buttons event handler"
#define DS4_BTN_EVENT_TASK_PRIORITY 7

#endif // BTN_EVENT_HANDLING_SETTINGS_H
